spring:
  datasource:
    url: 'jdbc: mysql://localhost:3306/spring_recipe_prod'
    username: styles
    password: Styles1234#
  jpa:
    hibernate:
      ddl-auto: validate
    datbase-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true